version: '3.3'

services: 

    mysqlmaster:
        image: mariadb:latest
        container_name: master
        restart: always
        environment: 
            
            MYSQL_DATABASE: registration
            MYSQL_USER: root
          
            MYSQL_ROOT_PASSWORD: pass123
        ports: 
            - "3306:3306"
        networks: 
            - app-network

    phpmyadmin:
        depends_on: 
            - mysqlmaster
        image: phpmyadmin/phpmyadmin
        restart: always
        environment:
            PMA_HOST: master
            PMA_USER: root
            PMA_PASSWORD: pass123
           
        ports:
            - "8008:80"
        networks: 
            - app-network

    php:
        depends_on: 
            - mysqlmaster
    
        image: php:7.4-fpm
        privileged: true
        restart: always
        working_dir: /var/www/html
        volumes: 
            - ./kiosk:/var/www/html
              
        ports: 
            - "9000:9000"
        networks: 
            - app-network
    
    mynginx:
        depends_on: 
            - php
        image: nginx:latest
        privileged: true
        restart: always
        working_dir: /var/www/html
        volumes: 
            - ./kiosk:/var/www/html:rw
            - ./kiosk/nginx.ini:/etc/nginx/conf.d/default.conf:ro
            - ./kiosk/php-fpm.conf:/etc/php/7.4/fpm/php-fpm.conf:ro
            - ./kiosk/www.conf:/etc/php/7.4/fpm/pool.d/www.conf:ro

        container_name: mynginx
        ports: 
            - "8080:80"
        networks: 
            - app-network


networks: 
    app-network:
        driver: bridge