version: '3.3'

services: 

    mysql:
        image: mariadb:latest
       
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: pass123
            MYSQL_DATABASE: registration
            MYSQL_USER: root
            MYSQL_PASSWORD: pass123
        ports: 
            - "3306:3306"
        networks: 
            - app-network

    phpmyadmin:
        depends_on: 
            - mysql
        image: phpmyadmin/phpmyadmin
        restart: always
        environment:
            PMA_HOST: master
            PMA_USER: root
            PMA_PASSWORD: pass123
            PMA_PORT: 3306
        ports:
            - "8004:8004"
        networks: 
            - app-network

    myphp:
        depends_on: 
            - mysql
    
        build: ./kiosk/php
        privileged: true
        restart: always
        working_dir: /var/www/html
        volumes: 
            - ./kiosk:/var/www/html
              
        ports: 
            - "9000:9000"
        networks: 
            - app-network
    
    mynginx:
        depends_on: 
            - myphp
        image: nginx:latest
        privileged: true
        restart: always
        working_dir: /var/www/html
        volumes: 
            - ./kiosk:/var/www/html
        container_name: mynginx
        ports: 
            - "8080:80"
        networks: 
            - app-network


networks: 
    app-network:
        driver: bridge