version: '3.3'

services: 

    mysqlmaster:
        image: mariadb:latest
        container_name: master
        restart: always
        environment: 
            
            MYSQL_DATABASE: registration
            MYSQL_USER: root
          
            MYSQL_ROOT_PASSWORD: pass123
        ports: 
            - "3306:3306"
        networks: 
            - app-network

    phpmyadmin:
        depends_on: 
            - mysqlmaster
        image: phpmyadmin/phpmyadmin
        
        environment:
            PMA_HOST: master
            PMA_USER: root
            PMA_PASSWORD: pass123
           
        ports:
            - "8008:80"
        networks: 
            - app-network

    myphp:
        depends_on: 
            - mysqlmaster
        image: php:7.4-fpm
        build: ./src/php
        privileged: true
        restart: always
        working_dir: /var/www/html
        volumes: 
            - ./kiosk:/var/www/html
              
        ports: 
            - "9000:9000"
        networks: 
            - app-network
        deploy: 
            mode: replicated
            replicas: 2
            restart_policy:
                condition: on-failure
    
    

    nginx:
        depends_on: 
            - myphp
        image: nginx:latest
        container_name: mynginx
        privileged: true
        restart: always
        working_dir: /var/www/html
        volumes: 
            - ./kiosk:/var/www/html:rw
            - ./src/nginx.ini:/etc/nginx/conf.d/default.conf:ro
            - ./src/php-fpm.conf:/etc/php/7.4/fpm/php-fpm.conf:ro
            - ./src/www.conf:/etc/php/7.4/fpm/pool.d/www.conf:ro
        ports: 
            - "8080:80"
        networks: 
            - app-network


networks: 
    app-network:
        external: 
            name: app-network